### PR TITLE
multi threading improvements

### PR DESCRIPTION
**Pull request by osch**
As discussed in issue #5 here comes a solution that does only allow one lua main thread to require module `moonfltk`. This foreground lua main thread is stored in a global variable and used for all callback processing that is invoked by FLTK. All other lua main threads can load the module `moonfltk.background` with restricted operations that are save if invoked from other lua main threads, most important of course `fl.awake`.

### CODE REVIEW

**Comment by osch** [comment]
I also tried the luajack example script that uses moonfltk, this works with current master. Than I improved the example to use `fl.awake()` and this does also work and uses less CPU :-)
I added the example to current master.

**Comment by stetre** [comment]
Nice :) Is this ready for merging, or are you still working on it?

**Comment by osch** [comment]
Yes, I think this can be merged now (I just push-forced the doc/index.html file that was removed by `make clean`). I'm working next on implementing further things, e.g. `fl.set_boxtype` and while doing this thoroughly check the multithreading / multistate aspect.

**Comment by stetre** [comment]
OK, I'll merge it, then. Thank you!
(While investigating I also spotted another problem. I'll fix it after merging.)

**Pull request merged**
