### PR TITLE
multi threading

### PR DESCRIPTION
**Pull request by osch**
Hi Stefano,

I implemented missing fltk multi threading functions for moonfltk and created also an example to demonstrate how LuaLanes (https://github.com/LuaLanes/lanes) can be used together with moonfltk.

What do you think?

Best regards,
Oliver

### CODE REVIEW

**Comment by stetre** [comment]
Hi Oliver, first of all, thank you for your contributions!

To be honest, I'm not familiar with LuaLanes and I'm not sure about the implications of adding multithreading to this library, but since lock() and unlock() are just bindings, I think it's safe to add them (with a "use at your own peril" disclaimer ;-).

Can you please add a (void)L; statement at the beginning of the Unock() function, to avoid the 'unused parameter' warning? 

Ste.

**Comment by osch** [comment]
I'm currently working on improving the fl.awake function, because I discovered in the FLTK documentation, that the default FLTK message handler only saves the last AwakeMessage.....

**Comment by osch** [comment]
@stetre, the good thing is, that the FLTK-multi-threading functions are independant from the threading library. So using LuaLanes ist just one option. There are other lua multi-threading libraries available, see for example the comparison at: http://lualanes.github.io/lanes/comparison.html

So it's a good thing to add a binding to the FLTK-multi-threading functions, which offers a lot of possibilities for the MoonFLTK library.

> Can you please add a (void)L; statement at the beginning of the Unock() function, to avoid the 'unused parameter' warning?

Yes of course, I'm adding this just now....

**Comment by osch** [comment]
Thank you for merging :-) I'm opening another pull request for improving the awake function...

**Pull request merged**
