### PR TITLE
fl.set_boxtype, fl.get_box_type & fl.args

### PR DESCRIPTION
**Pull request by osch**
Hi Stefano,
here comes my implementation for fl.set_boxtype, fl.get_box_type & fl.args. What do you think?
Best regards,
Oliver

### CODE REVIEW

**Comment by stetre** [comment]
Hi Oliver, great job as usual.
Apart from a missing return statement at the end of the `Args` function (file `fl.cc`), I see a small problem that however can be worked around.

It seems to me that the new `check_Boxtype` implementation breaks the euristics used by the `fl.box` method (`BOX_NEW` macro, file `func.h`) to determine if the first parameter is the box type or the x coordinate. Currently it does so by checking if it is a string or an integer, but now that the boxtype itself may be an integer we need to change the euristics, e.g. by checking if - being the first parameter an integer - there are 4 or 5 of them.

**Comment by osch** [comment]
ah yes, good point, I didn't see this. I will provide a correction as you suggested...

**Comment by stetre** [comment]
I think it is enough to just check the 5-th parameter.

**Comment by osch** [comment]
Here comes the fix. Moreover `check_Boxtype` also needed a fix because `lua_isstring` is also `true` for integer ;-)

**Comment by stetre** [comment]
Oops.. I've got bitten a few times by this.
May I merge?

**Comment by osch** [comment]
Yes :-)

**Comment by stetre** [comment]
Allright then :-) 
The manual also needs to be updated. I may do it myself but in a few day from now (I'm currently working on other stuff, and I'll need some time to switch my head back to this messy codebase....).

Again, thank you!

**Comment by osch** [comment]
> The manual also needs to be updated. I may do it myself

Thank you, this would be great!

**Pull request merged**
