### PR TITLE
Eliminate main_lua_state.

### PR DESCRIPTION
**Pull request by ComputerNerd**
This patch gets rid of main_lua_state. This is good because that means there is one less global variable. Also it is important if you have multiple instances of lua_State.

### CODE REVIEW

**Comment by stetre** [comment]
I'm afraid that this would break PR #7, where the global main_lua_state was introduced.

**Comment by ComputerNerd** [comment]
I was not aware of this when I made this pull-request/patch. I think @osch should comment on this if he is available. It seems like he is trying to solve a different problem than I am. I think there could be a way to handle both his use case and mine with the same code.

I am currently using moonfltk in my project (https://github.com/ComputerNerd/Retro-Graphics-Toolkit). I use Lua for two things.
1. Configuring the program and also some GUI elements are implemented via Lua. All of this is done in its own Lua state.
2. Running user made scripts. This gets its own Lua state so that way people won't accidentally change variables that are in the other Lua state.
These two events never occur at the same time and because of this I don't have threading issues.

**Comment by osch** [comment]
Did you read #5? There is explained in detail what problem was solved and why the current solution was chosen. 

If you simply store the Lua state that was active when registering the callback you cannot be sure that this Lua state is still alive when the callback is to be executed. This is not only multi-threading it can also occur in single threaded Lua if you are using coroutines (in fact each coroutine is a separate Lua state).

FLTK itself is inherently based on global variables, therefore choosing a global variable for storing a Lua state for handling callbacks is an adequate solution IMHO.

**Comment by ComputerNerd** [comment]
@osch Thank you for pointing me to #5. After thinking about this issue more I realized that the real problem is my application, not your solution. I will instead modify my application to only use one lua_State which will be valid for the lifetime of the program. For user made scripts people should be using local anyway.

**Comment by stetre** [comment]
You can sandbox user scripts running in the same lua_State by using [_ENV](http://www.lua.org/manual/5.3/manual.html#2.2) (you'll need Lua >=5.2 for this, though, if I remember correctly).

**Comment by ComputerNerd** [comment]
I like that solution because it gives the user the ability to choose if they want access to the application variables or not. If I find out that people don't want to add Lua code that uses ENV when needed I can also do it with the C API. Thank you for pointing this out.

**Pull request closed without merging**
